---
:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:timeout: 30
:verbose: <%= ENV.fetch("RAILS_ENV", "development") == "development" %>
:queues:
  - [broadcasts, 3]
  - [default, 2] 
  - [mailers, 1]
:max_retries: 3

# Redis configuration is handled in config/initializers/sidekiq.rb
# This ensures compatibility with Render's Redis service

# Schedule for recurring jobs
:schedule:
  expire_broadcasts_worker:
    cron: "0 * * * *" # every hour
    class: ExpireBroadcastsWorker
    queue: default