:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:queues:
  - [default, 1]
  - [broadcasts, 2]
  - [mailers, 1]
:max_retries: 3

# Redis URL (optional if you prefer environment variables)
:redis:
  :url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>


:cron:
  expire_broadcasts_worker:
    cron: "0 * * * *" # every hour
    class: "ExpireBroadcastsWorker"