# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
# Updated for RSpec 8 and Rails 8 compatibility
ENV['SECRET_KEY_BASE'] ||= 'test-secret-key-base-for-rspec-tests'

RSpec.configure do |config|
  # rspec-expectations config
  config.expect_with :rspec do |expectations|
    # Include chain clauses in custom matcher descriptions (default in RSpec 8)
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true

    # Enables syntax like `expect(actual).to eq(expected)` - this is already the default
    expectations.syntax = :expect
  end

  # rspec-mocks config
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object (default in RSpec 8)
    mocks.verify_partial_doubles = true

    # Verify doubled constant references (recommended for RSpec 8)
    mocks.verify_doubled_constant_names = true
  end

  # Shared context metadata behavior (default in RSpec 8)
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # RSpec 8 recommended settings (previously commented out)

  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax (recommended)
  # See: https://rspec.info/features/rspec-core/configuration/zero-monkey-patching-mode/
  config.disable_monkey_patching!

  # Use the documentation formatter for detailed output when running a single spec file
  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the end of the spec run
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies
  config.order = :random

  # Seed global randomization for reproducible test failures
  Kernel.srand config.seed

  # RSpec 8: Enable warnings to catch deprecations early
  config.warnings = true
end
