name: Render Deploy via CLI
run-name: Deploying to Render via CLI

# main 브랜치에 push될 때 실행
on:
  push:
    branches:
      - main
  workflow_dispatch: # 수동 실행 가능

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    name: Deploy API Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Render CLI 설치 (최신 버전 사용)
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v2.1.4/cli_2.1.4_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v2.1.4 /usr/local/bin/render
          render --version

      # API 서버 배포
      - name: Deploy API Server
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          echo "Deploying API server..."
          render deploys create srv-cvbri10fnakc73dntmsg --output json --confirm --wait
          echo "API server deployment completed!"

  deploy-sidekiq:
    runs-on: ubuntu-latest
    name: Deploy Sidekiq Worker
    needs: deploy-api # API 서버 배포 완료 후 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Render CLI 설치
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v2.1.4/cli_2.1.4_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v2.1.4 /usr/local/bin/render

      # Sidekiq 워커 배포
      - name: Deploy Sidekiq Worker
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          echo "Deploying Sidekiq worker..."
          render deploys create srv-cvlm6cbipnbc73as48ag --output json --confirm --wait
          echo "Sidekiq worker deployment completed!"

  post-deploy:
    runs-on: ubuntu-latest
    name: Post Deployment Tasks
    needs: [deploy-api, deploy-sidekiq]
    steps:
      - name: Install Render CLI
        run: |
          curl -L https://github.com/render-oss/cli/releases/download/v2.1.4/cli_2.1.4_linux_amd64.zip -o render.zip
          unzip render.zip
          sudo mv cli_v2.1.4 /usr/local/bin/render

      # 배포 후 서비스 상태 확인
      - name: Check Services Status
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          echo "Checking services status..."
          render services --output json --confirm | jq '.[] | select(.service) | {name: .service.name, status: .service.suspended, url: .service.serviceDetails.url}'
          
      # 로그 확인 (최근 10개)
      - name: Check Recent Logs
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: |
          echo "Checking recent API logs..."
          render logs --limit 10 -r srv-cvbri10fnakc73dntmsg --output text --confirm || true
          echo "Checking recent Sidekiq logs..."
          render logs --limit 10 -r srv-cvlm6cbipnbc73as48ag --output text --confirm || true 